### ISSUE TITLE
Plugin mangles post with multiple GitHub PR links in it

### ISSUE THREAD

**Issue by hmhealey** [mattermost/mattermost-plugin-autolink#19]
Using the config that's on pre-release.mattermost.com, posting multiple links to GitHub PRs in a single paragraph causes the post to become mangled. For example,
```
https://github.com/mattermost/mattermost-server/pull/9175 and https://github.com/mattermost/mattermost-server/pull/9175
```
becomes
```
[pr-mattermost-server/pull/9175 [pr-mattermost-server-9175](https://github.com/mattermost/mattermost-server-9175](https://github.com/mattermost/mattermost-server-9175](https://github.com/mattermost/mattermost-server/pull/9175) https://github.com/mattermost/mattermost-server/pull/9175)
```

**Comment by jespino** [comment]
This is probably fixed in some intermediate release, I would expect to the next release (I'll create it soon), and deploy the last version in to pre-release.

**Comment by mkraft** [comment]
I am still happening with v0.3.0. Example: https://community-daily.mattermost.com/private-core/pl/iwjgf3p1u7f73kqncoq6ps3iuh

<img width="1166" alt="Screen Shot 2019-04-09 at 7 37 32 AM" src="https://user-images.githubusercontent.com/1149597/55797483-956e2d80-5a9a-11e9-94d8-ef8f6dcc7c9c.png">

**Comment by hanzei** [comment]
@jespino Should this be fixed with `v0.4.0` or with the next release?

**Comment by jasonblais** [comment]
FYI @levb @jfrerich This is another bug which would get noticed and reported as an issue in a GA release. However, looks like @jespino may already have a fix for this

**Comment by levb** [comment]
https://mattermost.atlassian.net/browse/MM-15967 @jespino I see it still happening on community, and this is not specific to the regexp for github.

**Comment by hanzei** [comment]
It seams like `v1.0.0` has fixed this problem. Feel free to reopen if this is still an issue.

**Comment by jasonblais** [comment]
@levb Do we know what suddenly fixed this? I don't see anything in the commits that would have fixed this.

Maybe something on the Mattermost platform itself?

**Comment by hanzei** [comment]
I suppose it was fixed with https://github.com/mattermost/mattermost-plugin-autolink/pull/38

**Comment by jasonblais** [comment]
I see. Maybe we had an old version deployed on community.mattermost.com until v1.0.0 was deployed
